services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - internal_network
      - external_network
    env_file:
      - ./config/docker.env
    links:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    networks:
      - internal_network
    env_file:
      - ./config/docker.env
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:

networks:
  internal_network:
    internal: true
  external_network:
