services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    links:
      - db
    command: sh -c "npm install --force && npm uninstall prisma @prisma/client --force && npm install prisma@5.19.1 @prisma/client@5.19.1 --force && node server.js"
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quesdon
      - TZ=Asia/Seoul
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
